name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            g++ \
            libgtk-4-dev \
            libadwaita-1-dev \
            libfontconfig1-dev \
            libsoup-3.0-dev \
            libcurl4-openssl-dev \
            libjson-glib-dev \
            libglib2.0-dev-bin \
            blueprint-compiler

      - name: Configure
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --parallel $(nproc) --verbose

      - name: Debug output
        run: |
          echo "=== build directory ==="
          ls -R build || true
          echo "=== find binaries ==="
          find build -type f -executable || true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: PCL-CGRE-linux
          path: build/**
